### ISSUE TITLE
message_from option not sending as 'from' parameter

### ISSUE THREAD

**Issue by DJM0** [a2design-inc/hipster#1]
Not sure if you know about this, but when sending a message you require using the message_from option when sending a message. The API needs a valid 'from' parameter.

`hipchat.send_messages(room_id=553319, message_from='Test', message='Hello World!')`

`{'status': 400, 'data': '{"error":{"code":400,"type":"Bad Request","message":"Missing required parameter: from"}}'}`

**Comment by ghost** [comment]
Thanx, fixed.

**Comment by DJM0** [comment]
Thanks for having a look. But now the issue is 'from' is a reserved word in python terms. So you can't use it when calling the function. Not sure if i'm being silly here as my Python experience isn't great :/

**Comment by ghost** [comment]
To avoid this situation, use the dictionary, like this:
hipster.send_messages({
....
'from': your_id,
'message': your message
})
I'll correct this little oversight in the near future. Thank you.

**Comment by ghost** [comment]
Ok, I fixed it. Use 'sender' as named argument instead 'from'. 
Thank you for help in bug fixing.

**Comment by DJM0** [comment]
Great thanks for fixing it! :)
